
language: go

go:
  - master
services:
  -postgresql
before_install:
  - chmod +x clean.sh
  - chmod +x test.sh
before_script:
  - psql -c "CREATE DATABASE your_database;" -U postgres
  - psql -c "CREATE USER your_username WITH PASSWORD 'your_password';" -U postgres
script:
  - ./clean.sh
  - ./test.sh